apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: mysql
data:
  init.sql: |
    USE mysql_db;
    GRANT ALL PRIVILEGES ON mysql_db.* TO 'mysql_admin'@'%';
    FLUSH PRIVILEGES;