apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: mysql
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: bXlzcWw=
  MYSQL_DATABASE: bXlzcWxfZGI=
  MYSQL_USER: bXlzcWxfYWRtaW4=
  MYSQL_PASSWORD: bXlzcWxfYWRtaW5fcGFzc3dvcmQ=